sendToFriendInput:
  layout: layoutC
  customize:
    sendDraftButton:
      template: [message, sendDraftButton]
      parts   : [formMessage]
      target  : [formBottom]
all:
  has_layout:     on
  layout:         layoutB
  stylesheets: [/opMessagePlugin/css/message]

smtListSuccess:
  layout: smtLayoutHome

smtShowSuccess:
  layout: smtLayoutHome
  stylesheets: [/opTimelinePlugin/css/blueandgreen.css]
